name: openclip2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aria2=1.37.0=hbc8128a_2
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgomp=15.1.0=h767d61c_5
  - libiconv=1.18=h3b78370_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.4=h6a678d5_0
  - openssl=3.5.3=h26f9b46_1
  - python=3.9.18=h0755675_1_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
    - albucore==0.0.23
    - albumentations==0.5.2
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.9.0
    - appdirs==1.4.4
    - attrs==25.3.0
    - beautifulsoup4==4.13.4
    - black==25.1.0
    - bleach==6.2.0
    - braceexpand==0.1.7
    - certifi==2025.1.31
    - cffi==1.17.1
    - charset-normalizer==2.1.1
    - click==8.1.8
    - cloudpickle==3.1.1
    - contourpy==1.3.0
    - cryptography==45.0.4
    - cycler==0.12.1
    - dataclasses==0.6
    - detectron2==0.6
    - dill==0.4.0
    - distro==1.9.0
    - effdet==0.4.1
    - einops==0.8.1
    - eval-type-backport==0.2.2
    - exceptiongroup==1.2.2
    - exifread-nocycle==3.0.1
    - filelock==3.17.0
    - fire==0.5.0
    - flash-attn==2.7.4.post1
    - fonttools==4.56.0
    - fsspec==2025.3.2
    - ftfy==6.3.1
    - future==1.0.0
    - fvcore==0.1.5.post20221221
    - gitpython==3.1.44
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.29.1
    - hydra-core==1.3.2
    - idna==3.10
    - imageio==2.37.0
    - img2dataset==1.45.0
    - imgaug==0.4.0
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - iopath==0.1.9
    - jinja2==3.1.5
    - jiter==0.9.0
    - joblib==1.4.2
    - kaggle==1.7.4.5
    - kiwisolver==1.4.7
    - layoutparser==0.3.4
    - lazy-loader==0.4
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - mpmath==1.3.0
    - multiprocess==0.70.18
    - mypy-extensions==1.1.0
    - networkx==3.2.1
    - nibabel==5.3.2
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - omegaconf==2.3.0
    - open-clip-torch==2.31.0
    - openai==1.70.0
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.11.0.86
    - packaging==24.2
    - pandas==2.2.3
    - pathos==0.3.4
    - pathspec==0.12.1
    - pdf2image==1.17.0
    - pdfminer-six==20250506
    - pdfplumber==0.11.7
    - pillow==10.4.0
    - pip==25.1.1
    - platformdirs==4.3.6
    - poppler-utils==0.1.0
    - portalocker==3.2.0
    - pox==0.3.6
    - ppft==1.7.7
    - protobuf==4.25.7
    - psutil==7.0.0
    - pyarrow==15.0.2
    - pycocotools==2.0.10
    - pycparser==2.22
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pydicom==2.4.4
    - pydot==4.0.1
    - pyfreebody==0.4.2
    - pyparsing==3.2.1
    - pypdfium2==4.30.1
    - pytesseract==0.3.13
    - python-dateutil==2.9.0.post0
    - python-slugify==8.0.4
    - pytz==2025.1
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.3
    - scikit-image==0.24.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - sentencepiece==0.2.0
    - sentry-sdk==2.22.0
    - shapely==2.0.7
    - simsimd==6.2.1
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.7
    - stringzilla==3.12.3
    - sympy==1.13.1
    - tabulate==0.9.0
    - termcolor==3.0.1
    - text-unidecode==1.3
    - threadpoolctl==3.5.0
    - tifffile==2024.8.30
    - timm==1.0.15
    - tokenizers==0.21.0
    - tomli==2.2.1
    - torch==2.6.0
    - torchvision==0.21.0
    - tqdm==4.67.1
    - transformers==4.49.0
    - triton==3.2.0
    - typing-extensions==4.13.2
    - tzdata==2025.2
    - urllib3==1.26.20
    - wandb==0.16.6
    - wcwidth==0.2.13
    - webdataset==0.2.86
    - webencodings==0.5.1
    - werkzeug==3.1.3
    - yacs==0.1.8
    - zipp==3.21.0
prefix: /home/yiweilyu/.conda/envs/openclip2
